### ISSUE TITLE
export to pcap

### ISSUE THREAD

**Issue by Revent** [sipcapture/heplify-server#118]
Don't work pcap export in docker version.
file HOMER5-91.218.111.140-79088697999-8_3_2018\ 15_13_12.pcap 
HOMER5-91.218.111.140-79088697999-8_3_2018 15_13_12.pcap: data

**Comment by negbie** [comment]
Hi,
this is not related to heplify-server but the homer webapp container. See here
https://github.com/sipcapture/homer/issues/298

Please comment there if you need help. Otherwise you can install the gui by hand. See here:
https://github.com/sipcapture/heplify-server/tree/master/example/install/homer5

**Comment by negbie** [comment]
I will close this now. If you need any help tell me.
