### ISSUE TITLE
New metrics on Heplify-server

### ISSUE THREAD

**Issue by mcebey1891** [sipcapture/heplify-server#270]
Hi,

Sorry if this is not the way to ask this question.

I need to add some metrics to those generated by the Heplify-server for Prometheus.
The only way is to recompile the server or is there another way?

Thanks

**Comment by lmangani** [comment]
General answer is yes. This said - Could you be more explicit? What are you trying to achieve or implement?

**Comment by mcebey1891** [comment]
The metrics generated by the server are generic for each Node.

I need that in addition to relating the metric to the node, do it to the source and destination IPs.
I'm trying to make a graphic with a query of the style:

`heplify_rtcp_jitter{job="heplify-server",sorce_ip=<XX.XX.XX.XX>}`

**Comment by negbie** [comment]
Yes you need to recompile heplify-server when you change the metric definitions. Besides that keep in mind that what you are trying to do is against prometheus best practices. Using IP's as label values will result in metrics with high cardinality if you have lot's of different endpoints.

Things become better if you use VictoriaMetrics because it uses a LSM data structure whichs is better suited for high cardinality but it still has it's limit when your traffic grows and you have a lot of different IP's. In that case TimescaleDB can help you but it's not part of the open source edition on github.

Keep in mind that this applies only for a decent amount of traffic with lots of endpoints. If your network has only about 20000 different endpoints you can use almost everything ;)

**Comment by negbie** [comment]
Despite influxdb of course which will fall over at 10k or so depending on your hardware ;)
