### ISSUE TITLE
regex for SIP headers

### ISSUE THREAD

**Issue by kpribic** [sipcapture/heplify-server#310]
Would it be complicated to add regex functionality for extracting tags in SIP headers?
Idea is the same as for correlation ID where regex support was added to extract icid-value from p-charging-vector.
For example:

CustomHeader    = ["P-Charging-Vector,icid-value=\"?(.*?)(?:\"|;|$)"]

It would be useful if, for example, there is an external system billing that would generate search URL for HOMER that looks for icid-value, and it since it is separate it would be an indexed search and not full text search across SIP RAW field.

One open issue is what would be the field name in HEP. Maybe it could be specified explicitly somewhere in the CustomHeader, not sure where it makes sense.

**Comment by negbie** [comment]
@kpribic 
No that should be quite easy and since I'm very limited in time I would like to ask you if you are interested in implementing this?

You can take a look at @games130 commit here:
https://github.com/sipcapture/heplify-server/commit/e9ecc826b12e4a2a482f1b0a781d9770b0d4aedc

and adapt. You will need to move out the CustomHeader of the default case because currently CustomHeader will only be checked if there is no match with any of the known header like From, To and so on.

Another thing you need to consider is that this will come with a performance penalty because you will check every header.

**Comment by negbie** [comment]
I can offer you to review your commit later.

**Comment by negbie** [comment]
Another option would be to ask @lmangani if they are willing to invest some time in adding pipelines to heplify-server. I know that he is interested in this so maybe they can throw some manpower at this topic. In general it's quite easy and the important part is to do this concurrently. For this the foundation is already there. The other part would be to use a map for the hep type and using multiple pipeline stages like a filter stage and a transform stage which can manipulte the map. Than instead of passing the hep type around you would pass the map around. With this you could handle your case too.

**Comment by lmangani** [comment]
Absolutely, we'll work this one out at qxip

**Comment by kpribic** [comment]
It would be a long wait for me to implement this (as simple as it is for @negbie ), luckily qxip to the rescue :-)

PS @lmangani the URL search I mentioned, does this work on Homer7? Couldn't find any documentation except a rather empty ticket about time period definition via URL.

**Comment by lmangani** [comment]
@kpribic not sure what you mean please open a separate ticket for the URL question or we'll miss the point here :)

**Comment by kpribic** [comment]
OK, you're right, sticking to the point :-)

**Comment by negbie** [comment]
@kpribic Another thing you can do is to use Grafana explore and Loki. We use it for some correlation stuff. In Newer versions of Grafana you can set Derived fields in the Loki Datasource. Take a look here:

https://grafana.com/docs/grafana/latest/features/datasources/loki/#derived-fields

**Comment by kpribic** [comment]
Thanks @negbie, I'll check it out.

**Comment by games130** [comment]
> Another option would be to ask @lmangani if they are willing to invest some time in adding pipelines to heplify-server. I know that he is interested in this so maybe they can throw some manpower at this topic. In general it's quite easy and the important part is to do this concurrently. For this the foundation is already there. The other part would be to use a sync.map for the hep type and using multiple pipeline stages like a filter stage and a transform stage which can manipulte the map. Than instead of passing the hep type around you would pass the map around. With this you could handle your case too.

@negbie if we are to use MAP instead of HEP type, this would provide a more flexible transformation right? however this would mean quite a large change as we would need to get all HEP type to be change to MAP instead. example SIP parser would need to return MAP, then in between the parser to inserting to the database will need to be change to accept MAP too right?

**Comment by negbie** [comment]
@games130 yes but I would come with some costs. First it will need quite a bit of refactoring and of course it will hurt performance. If you don't want to change a lot of code you can start with a map embedded into the HEP type. Of course this will still hurt performance a bit because of extra allocations but wouldn't require a big refactoring.

**Comment by lmangani** [comment]
@games130 we will not use MAP instead of HEP, it would equal throwing away 10 years of integrations and smart solutions for no gain at all. This sort of extraction can be done by our advanced HEP agents and servers both already without any such changes (HEP is extensible and can contain whatever one wants) but quite transparently, this is  one of the feature we currently ship in our commercial products and use to sponsor the (otherwise free and extremely expensive) Homer stack development and roadmap. Feel free to contact us for options which are either contributing, sponsoring or purchasing this feature.

**Comment by negbie** [comment]
@games130 but if you come up with a good solution for this in heplify-server you can of course contribute! Everyone is welcome!

**Comment by games130** [comment]
@lmangani I see this thread is now closed. just checking if the original request have a solution already? 

Also, just for discussion -- I am not saying that between the client and server need to change to MAP. That will still maintain as HEP, but the heplify-server internal processing would have to parse the received HEP message into a MAP for further processing.

**Comment by lmangani** [comment]
@games130 thanks its good to know this is assumed correctly - just remember, HEP has been designed for custom chunk support and there's no reason to centralize a task you can effectively distribute to the workers already parsing the same messages - just my 2 cents. Contributions are always welcome!

**Comment by games130** [comment]
@lmangani Just checking that i understand what you are saying. When you say distribute to the workers.. This would be the heplify clients right? So they would do some data transformation before sending it to heplify-server?

**Comment by lmangani** [comment]
@games130 that's the approach i would consider for static rules in general and to leverage the HEP features and minimize the server-side changes required to leverage them. Others might see this differently, so its a personal view.

**Comment by games130** [comment]
@kpribic are you still waiting for a solution to this issue?
If yes, can you give me more information and an example as well.
I am looking to try to more data transformation (remove prefix in callID for call corellation). Mabye can see how this can be done in a more universal way.

**Comment by kpribic** [comment]
What I wanted to achieve here was specifically icid-value tag from p-charging-vector header as separate value in json in database so that I don't have to do some sort of substring matching when doing a DB search. (Next step would be to expand URL search to match specifically for this value.)

In broader sense it means access to tags for headers that are already parsed out and recorded in json for search purposes for any header.

There was mention of pipelining that would solve this, but honestly I'm not entirely clear on what pipelining is in this context nor if there is projected timeline for implementation.

**Comment by games130** [comment]
@kpribic i guess you are using homer7 + postgres? All these while i am still using homer5 + mysql.
Anyway i try looking at your request. Please do help me out as well.

Starting from the begining, i see the calls will be store in hep_proto_1_call with the table
    Column      |           Type           
----------------+--------------------------
id              | bigint                   
sid             | character varying        
create_date     | timestamp with time zone 
protocol_header | jsonb                    
data_header     | jsonb                    
raw             | character varying        

If we are just looking at the regex for AlegIDs(specifically icid-value tag from p-charging-vector), this regex result is never stored within the DB except as a raw. is that correct?

If that is so, would storing the regex result(extract icid-value tag from p-charging-vector) in data_header help you?

**Comment by kpribic** [comment]
> @kpribic i guess you are using homer7 + postgres? All these while i am still using homer5 + mysql.

Well, to be honest, I'm running Homer5 on production and sending partial data to Homer7. I personally use Homer7 for troubleshooting daily, but I'm still working on integration for other people to use it.

> Anyway i try looking at your request. Please do help me out as well.

Whatever I can :-)

> Starting from the begining, i see the calls will be store in hep_proto_1_call with the table
> Column | Type
> ----------------+--------------------------
> id | bigint
> sid | character varying
> create_date | timestamp with time zone
> protocol_header | jsonb
> data_header | jsonb
> raw | character varying
> 
> If we are just looking at the regex for AlegIDs(specifically icid-value tag from p-charging-vector), this regex result is never stored within the DB except as a raw. is that correct?

Correct.

> If that is so, would storing the regex result(extract icid-value tag from p-charging-vector) in data_header help you?

That is exactly what I would like. For example below is a `data_header` example: whole P-Charging-Vector is extracted via current heplify-server config and what I need is that last line where icid-value would be extracted as separate value in json.
```
{
  "cseq": "102 INVITE",
  "X-CID": "57aP0030001020HUbeGhEfCeJeJ0m",
  "callid": "343f064901299b584789b5d810c05218",
  "method": "INVITE",
  "to_user": "XXXXXXXXXXXX",
  "from_tag": "as3ae6cda9",
  "from_user": "YYYYYYYYYYYY",
  "ruri_user": "XXXXXXXXXXXX",
  "user_agent": "Asterisk",
  "ruri_domain": "10.10.10.10",
  "P-Charging-Vector": "icid-value=lcbp4046o9ds2pk6lhb23oo5jhd0nilcibb6nidcdpj43hvc4200;icid-generated-at=10.10.10.22",
  "icid-value":"lcbp4046o9ds2pk6lhb23oo5jhd0nilcibb6nidcdpj43hvc4200"
}
```

**Comment by games130** [comment]
could you share with me your toml file, I need to confirm how you are currently getting the values into the data_header. I am guessing that you put "X-CID" and "P-Charging-Vector" under CustomHeader becasue i cannot find these field to be selectable under SIPHeader.

**Comment by kpribic** [comment]
Yes, I use Custom header
```
CustomHeader    = ["P-Charging-Vector","X-CID"]
```
For parsing icid-value this regex from example AlegID works, had this running for a while when I tried to use correlation field:

```
AlegIDs               = ["X-CID","P-Charging-Vector,icid-value=\"?(.*?)(?:\"|;|$)"]
```

**Comment by negbie** [comment]
I use only Homer5 too and all internal heplify-server developement at my company is based on Homer5 so what I can suggest you is to take a look at github.com/valyala/fasttemplate. Homer5 has already 3 custom header fields and with fasttemplate it's quite easy to do the filter/mapping logic so that you only need to change heplify-server code and don't need to touch homer5 codebase. If I remember it right I alreay use fasttemplate for SIPHeader in homer7 so you can take this as starting point.

**Comment by games130** [comment]
@negbie yes thats where i am going to edit it. I saw that you have made it quite simple to add new headers. Thanks for that

@kpribic are you able to build from source? I added your request in my forked version(exactly same with sipcature/heplify-server). I dont see the added code can break anything but its better to have it tested before i do a pull request here. If you can help test it, you may pull the updated code from https://github.com/games130/heplify-server

Just update you toml to include "callid_aleg" in SIPHeader
`SIPHeader       = [......,"callid_aleg",......`

You should be able to see callid_aleg with the filtered regex(as specified in AlegIDs) in `data_header` I use callid_aleg since it is more generic and that name is already being used as well in the code.

```
{
  "cseq": "102 INVITE",
  "X-CID": "57aP0030001020HUbeGhEfCeJeJ0m",
  "callid": "343f064901299b584789b5d810c05218",
  "method": "INVITE",
  "to_user": "XXXXXXXXXXXX",
  "from_tag": "as3ae6cda9",
  "from_user": "YYYYYYYYYYYY",
  "ruri_user": "XXXXXXXXXXXX",
  "user_agent": "Asterisk",
  "ruri_domain": "10.10.10.10",
  "P-Charging-Vector": "icid-value=lcbp4046o9ds2pk6lhb23oo5jhd0nilcibb6nidcdpj43hvc4200;icid-generated-at=10.10.10.22",
  "callid_aleg":"lcbp4046o9ds2pk6lhb23oo5jhd0nilcibb6nidcdpj43hvc4200"
}
```

**Comment by stephanomarques** [comment]
Hi!
Having the exact same interest in obtaining the icid-value from P-Charging-Vector in the header as @kpribic mentioned earlier. I followed up by updating my config file to include SIPHeader = [......,"callid_aleg",......] as previously commented by @games130. 

I went on to verify these changes in the DB and saw that:
1. The protocol_header-> "correlation_id" does successfully retrieve the icid value, which is great.

**but**

2. when i go on to check other DB entries that dont possess P-Charging-Vector icid values and their respective protocol_header values, the correlation_id is occupied with the respective values of its call_id, which pretty much loses its purpose, because I just need this header_field to be written only by P-Charging-Vector icid values.

Could anyone assist in this matter?

**Comment by kpribic** [comment]
> @kpribic are you able to build from source? I added your request in my forked version(exactly same with sipcature/heplify-server). I dont see the added code can break anything but its better to have it tested before i do a pull request here. If you can help test it, you may pull the updated code from https://github.com/games130/heplify-server

Sorry @games130 I somehow managed to completely miss your response, yes I can build and I'll test it tomorrow.

**Comment by kpribic** [comment]
> 1. when i go on to check other DB entries (that dont possess P-Charging-Vector icid values) and their respective protocol_header, the correlation_id is occupied with the values of its call_id, which pretty much makes this lose it's purpose (I would later on proceed to map this in the homer-ui to be able to search for p-charging-vector values), because I need these header fields to only possess P-Charging-Vector icid values.
> 
> Could anyone assist in this matter or am I missing the point?

That issue can be solved by adding `"append_sid": true` in mappings. It should pick up missing messages in all scenarios by session_id in second pass.
See this for more details: https://github.com/sipcapture/homer-app/issues/278

**Comment by stephanomarques** [comment]
Sorry, I think you misunderstood what I was asking. How can I stop the P-Charging Vector icid values in the protocol_header->'correlation_id' from being occupied by call id ? I want it to remain empty if there is no P-Charging-Vector included in that message.

**Comment by kpribic** [comment]
Off the top of my head I think that behavior is hardcoded in heplify-server, not configurable.

My point was it doesn't really matter for correlation purposes as long as there is one message in dialog with the *right* correlationid value, homer-app will find all relevant messages given proper mapping.

**Comment by games130** [comment]
> Sorry, I think you misunderstood what I was asking. How can I stop the P-Charging Vector icid values in the protocol_header->'correlation_id' from being occupied by call id ? I want it to remain empty if there is no P-Charging-Vector included in that message.

Could you help me understand why you would want to do that? As kpribic mention the correlation_id is hardcode to use call id. i would assume the reason being call id would always be present in SIP where as the other correlation IDs might or might not be there.

**Comment by stephanomarques** [comment]
Using the image attached as an example, I can see that there are only 2 entries of all demonstrated that represent the P-Charging-Vector ICID. How? because the Correlation_id != Call_id.
I can filter this out easily in sql but i'm having a hard time figuring out how to make this happen in the correlation mapping of HOMER in JSON.

https://github.com/sipcapture/homer-app/wiki/Examples:-Correlation-MAPPING has an example of:
select * from hep_proto_100_default where sid = 'CALLID';

For my current problem I want to do:
select * from hep_proto_1_call where correlation_id != 'CALLID';

This would help me filter out any correlation_id that doesn't have a P-Charging-Vector ICID value.

How would I achieve this in the mapping? I'm having a hard time with lack of documentation.

![SharedScreenshot](https://user-images.githubusercontent.com/59531590/82547827-3fe7c980-9b52-11ea-87e9-9aa035efdc0f.jpg)

**Comment by adubovikov** [comment]
Next week we will make a new version of heplify-server with some additional features. Do you want to test it ?

**Comment by kpribic** [comment]
> @kpribic are you able to build from source? I added your request in my forked version(exactly same with sipcature/heplify-server). I dont see the added code can break anything but its better to have it tested before i do a pull request here. If you can help test it, you may pull the updated code from https://github.com/games130/heplify-server


I tested with config:
```
AlegIDs               = ["X-CID","P-Charging-Vector,icid-value=\"?(.*?)(?:\"|;|$)"]
SIPHeader       = ["callid","method","ruri_user","ruri_domain","from_user","from_domain","from_tag","to_user","to_domain","to_tag","contact_user","callid_aleg"]
```
And INVITE that doesn't have X-CID and it works as expected. 100 trying message in the same dialog didn't have anything in the callid_aleg field:

![image](https://user-images.githubusercontent.com/50572561/82555948-15553b00-9b69-11ea-92f0-33195eda0e4f.png)

I still have to try when there is X-CID in the message, it's a bit difficult to simulate in my environment at this moment, will get back with that test later.

**Comment by games130** [comment]
Looking at my own SIP trace, the SIP 100 respond does not contain "P-Charging-Vector".. therefore the callid_aleg will be empty since there is nothing for it to extract.

I dont have X-CID in my enviroment but i do have X-BroadWorks-Correlation-Info, it is not included in the SIP 100 respond as well. So i would have to assume this would be the same behaviour for X-CID as well.

with the change(adding callid_aleg), how does this affect your correlation?

**Comment by kpribic** [comment]
No, this is great, where there is icid-value to be had there is a header, and where there is no value there is no header at all.

For me this improves things a bit:
1) makes it cleaner, like stephano mentioned people get confused when correlationID changes value in dialog, I can use separate rules to correlate for logs using icid-value, while x-cid is used just to connect the SIP part together.
2) now there will  be a separate field for searching icid-value explicitily that will be properly named in GUI, and the field will be exact match not substring match in DB
3) when querying external systems I could be able to explicitly ask only for exact icid-value (this may require some development, currently it asks only for call-ids)
