### ISSUE TITLE
Kubernetes Helm Chart

### ISSUE THREAD

**Issue by clintberry** [sipcapture/heplify-server#35]
I am loving all your most recent work, guys. Way to go. We have heplify-server running in kubernetes now. Would you be interested in us creating a Helm chart/package for kubernetes deployments? It would take some work to get flexible enough for general deployments, but we can get there.

**Comment by lmangani** [comment]
Thanks @clintberry much of the credit goes to @negbie - and as usual, all contributions are welcome!
There's much more coming in the next weeks, and we hope this might lead to further cooperation, too

**Comment by clintberry** [comment]
Sounds good, we will start contributing the kubernetes stuff.

**Comment by negbie** [comment]
Thanks @clintberry. That would be really cool and a big help, because it's one point on my todo list anyway. At some point I want to focus more to integrate heplify-server into a message queue system( most likely nats) and kubernetes would be very handy here. Kubernetes, Prometheus and the new nodejs apiserver/GUI play also very well together. 

Keep in mind heplify-server is not final yet so some flags will change. Before my vacation I removed some of them to simplify stuff (drop TCP since go has such a superb TLS performance, drop protobuf flag and decide on runtime if its proto or hep, drop hepworkers for a value depending on actual load and CPU cores) and some more uncommitted changes.
