### ISSUE TITLE
Configure Node_id

### ISSUE THREAD

**Issue by mcebey1891** [sipcapture/heplify-server#359]
Hello,

I am using homcker-prom-all docker version. I have two CAPTAGENT probes.
When Grafana references traffic from each probe, it does so with a node_id that is a number like 131137536 that is not representative of the probe.
I would like to modify this node_id so that it has reference to the probe I am viewing.
Is there a way to do that?

Thank you

**Comment by negbie** [comment]
If you don't want to change your current setup I would recommend you to take a closer look at this https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

With Prometheus you can change your labels. Otherwise you could use heplify as capture client and  use the -hn flag to set a nodename instead of a nodeid.

**Comment by mcebey1891** [comment]
Thanks, I will try this way.

**Comment by mcebey1891** [comment]
It works, thanks!
