### ISSUE TITLE
Grafana Variable with IP

### ISSUE THREAD

**Issue by qttrl** [sipcapture/heplify-server#390]
Is it possible with the Grafana dashboards from homer to define variable with IP of SIP client and present metrics from Prometheus from a specific IP instead of overall statistics?

**Comment by negbie** [comment]
Yes just configure PromTargetIP and PromTargetName in heplify-server.toml like this:

PromTargetIP = "1.1.1.1, 2.2.2.2"
PromTargetName = "Asterisk1, Asterisk2"

Keep in mind that order is important. With that everything from or to IP 1.1.1.1 will get the Prometheus label Asterisk1 and  everything from or to IP 2.2.2.2 will get the Prometheus label Asterisk2

**Comment by stephanomarques** [comment]
Hi @negbie, I have a question regarding this issue. When inserting PromTargetIP and PromTargetName, for example: 

PromTargetIP = "1.1.1.1, 2.2.2.2"
PromTargetName = "Asterisk1, Asterisk2"

As for my understanding heplify-server checks src/dst IP of packet and if matching PromTargetIP it labels with the PromTargetName (target_name="..."). 
The thing is, I don't want to scrape specifically for every target, so imagine I have 3.3.3.3 and 4.4.4.4 traversing heplify-server but I'm not interested in seeing specific metrics for them but rather overall metrics of both. Is there a way or special char that represents all other IP's so I can get overall and specific metrics, for example:

PromTargetIP = "*,1.1.1.1, 2.2.2.2"
PromTargetName = "*,Asterisk1, Asterisk2"

Where * represents every other IP and is assigned the same target_name so that metrics are being scraped from them and I can still have an overall view of them, and specific view for 1.1.1.1 2.2.2.2.
