### ISSUE TITLE
Homer 7 Metrics

### ISSUE THREAD

**Issue by ahelbadry** [sipcapture/heplify-server#440]
Hello, 

I would like to elaborate how much I'm stunned by the solution,

  I would like to ask about the ability of adding a RTCP packet drops in percentage, I tried adding a graph using values from Prometheus but no luck, also want to ask about the ability to add sip qualify number per trunk.

**Comment by negbie** [comment]
Happy to hear that. As far as I can remember I expose how many RTCP packets were captured. So with a litle bit of math in Prometheus you should be able to build a metric yourself which does that. Since SIP qualify number per trunk will generate high cardinality metrics which will hurt Prometheus performance it's not supported. Will close this since it's not really a issue but feel free to comment below.
