### ISSUE TITLE
SDP packet indicator in flow view

### ISSUE THREAD

**Issue by solarmon** [sipcapture/heplify-server#476]
Hi,

When I use sngrep, I find it useful when it shows a "(SDP)" text on a packet that has SDP in it.

However, in the Homer 7 web GUI in the flow view of the trace, you have to go in to the packet to see if there is any SDP details in it.

Can the flow view be changed to give an indication of whether SDP is present in a packet or not, without having to open it up. If the same behaviour as sngrep to add "(SDP)" to the packet name (ideally in a different colour) then that would be great!

Thank you!

**Comment by lmangani** [comment]
As discussed in the HOMER matrix channel, the Call-Flow should do exactly what you're describing already, so this might be a UI bug. Despite this, it doesn't belong into heplify-server. Since I cannot move issues between projects, could you please reopen in https://github.com/sipcapture/homer which is general purpose.

Thanks

**Comment by solarmon** [comment]
Apologies for raising this in the wrong channel.
