### ISSUE TITLE
heplify-server.toml

### ISSUE THREAD

**Issue by idanacontaqt** [sipcapture/heplify-server#522]
hey, is there any explanation for what each row is for? especially for the DB config

DBPartLog             = "2h"
DBPartSip             = "1h"
DBPartQos             = "6h"
DBDropDays            = 14
DBDropDaysCall        = 0
DBDropDaysRegister    = 0
DBDropDaysDefault     = 0
DBDropOnStart         = false
DBUsageProtection     = true
DBUsageScheme         = "percentage"
DBPercentageUsage     = "80%"
DBMaxSize             = "30MB"

thank you

**Comment by lmangani** [comment]
Sure, although those options are pretty much literally describing the usage. 

`DBPart*` = size of partitions for the various types
`DBDropDays*` = rotation in days for the various types
`DBDropOnStart` = triggers rotation drop on start
`DBUsageScheme` , `DBPercentageUsage` = rotate based on disk utilization rather than fixed days

You can check out the code and our examples to see what they do in full detail, but most likely you want to leave them as default unless you're running in a performance or scaling issue.

Hope this helps

**Comment by idanacontaqt** [comment]
So when DB capacity reach 80%, the database will drop all new logs? if so, then until when?

**Comment by idanam-del** [comment]
Bump
