### ISSUE TITLE
Missing src_id, dst_id, ID labels

### ISSUE THREAD

**Issue by ijozic** [sipcapture/heplify-server#524]
Hello. At some point, heplify server removed these labels from logs sent to loki and since we need them for some Grafana graphs, we had to revert all the way back to 1.30 as it's the last version with a release tag. Is there some config which would allow these to be set again in the newest releases (i.e. /latest)? Thanks.

**Comment by lmangani** [comment]
@ijozic IP fields are bad labels due to high cardinality. Group tagging is the way to go.

**Comment by ijozic** [comment]
Do you have some example somewhere on how we could configure this on the heplify server so that its HEP packets will have proper tags based on the source and destination IPs?

**Comment by ijozic** [comment]
Thanks, I'll give it a go.

**Comment by alexbakker** [comment]
I noticed that a new option (``LokiIPPortLabels``) was introduced for this. Would it make sense to optionally expose the PromTargetName as Loki labels as well (``src_name`` and ``dst_name``) in case the ``src_ip`` or the ``dst_ip`` of a HEP packet matches a PromTargetIP? Since pairs of ``{src,dst}_ip`` and ``{src,dst}_name`` should always be the same, it shouldn't worsen cardinality.
